### ISSUE TITLE
Gérer le XOR

### ISSUE THREAD

**Issue by Tunin05** [Tunin05/Prosit_2_Encryption#3]
Actuellement l'écriture du fichier modifie le contenu à crypter ce qui rend impossible le décryptage

**Comment by Kazmasan** [comment]
c'est de la merde

**Comment by Steeven-1002** [comment]
Des idées de solution ?

**Comment by Kazmasan** [comment]
peut-être demander à des personnes compétentes

**Comment by loloxd11** [comment]
> c'est de la merde

Je vous prie de garder un langage approprié. Merci
